search_field = '//div[@id="products_grid"]//input[@name="search"]'
sumit_button = '(//*[@type="submit" and @class="btn oe_search_button btn btn-light"])[1]'
found_table = '//a[@class="text-primary text-decoration-none"]'
steel_checkbox = '(//aside//label[contains(normalize-space(),"Steel")])[1]'
steel_table = '//*[@class="text-primary text-decoration-none"]'
table = '//*[@alt="Customizable Desk"]'
table_name = '//*[@class="text-primary text-decoration-none"]'
cart = '//*[@class="btn btn-primary a-submit"]'
modal = '//*[@class="modal-body oe_advanced_configurator_modal"]'
